services:
  web:
    image: nginx:alpine
    volumes:
      - ./backend:/var/www
      - ./docker/development/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "${NGINX_PORT}:80"
    networks:
      - app-development
    depends_on:
      php-fpm:
        condition: service_started
      vuejs:
        condition: service_started
  vuejs:
    build:
      context: .
      dockerfile: ./docker/development/vue/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    # develop:
    #   watch:
    #     - path: ./frontend/src
    #       target: /app/src
    #       action: sync
    #     - path: ./frontend/package.json
    #       target: /app/package.json
    #       action: restart
    #     - path: ./frontend/vite.config.js
    #       target: /app/vite.config.js
    #       action: restart
    networks:
      - app-development
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/development/php-fpm/Dockerfile
      target: development
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/var/www
      - /var/www/vendor
    networks:
      - app-development
    depends_on:
      mysql:
        condition: service_started
  php-cli:
    build:
      context: .
      dockerfile: ./docker/development/php-cli/Dockerfile
      target: development
    tty: true
    stdin_open: true
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/var/www
    networks:
      - app-development
  mysql:
    image: mysql:8.0.44
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql-db-dev:/var/lib/mysql
    networks:
      - app-development
networks:
  app-development:
    driver: bridge
volumes:
  mysql-db-dev:
