services:
  wed:
    build:
      context: .
      dockerfile: ./docker/production/nginx/Dockerfile
      target: production
    restart: unless-stopped
    volumes:
      # :ro - read only option
      # - laravel-public-assets:/var/www/public/build:ro
      - laravel-storage-production:/var/www/storage:ro
    ports:
      - "${NGINX_PORT}:80"
    networks:
      - app-production
    depends_on:
      php-fpm:
        condition: service_healthy
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/production/php-fpm/Dockerfile
      target: production # Specifies the build stage in the Dockerfile to be used
    restart: unless-stopped # Keeps the container alive unless it was manually stopped by the user
    # Mount the internal container directory to the volume name defined in the top-level volumes section
    volumes:
      # - laravel-public-assets:/var/www/public/build
      - laravel-storage-production:/var/www/storage
    env_file: # Specified .env file used container after building
      - ./backend/.env
    networks:
      - app-production
    healthcheck:
      test: ["CMD-SHELL", "php-fpm-healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      mysql:
        condition: service_healthy # Ensure that the dependencies is healthy before starting the service.
  php-cli:
    build:
      context: .
      dockerfile: ./docker/production/php-cli/Dockerfile
      target: production
    tty: true # Enables an interactive terminal
    stdin_open: true # Keeps standard input open for 'docker exec'
    env_file: # Specified .env file
      - ./backend/.env
    networks:
      - app-production
  mysql:
    image: mysql:8.0.44 #Pull the MySQL image from Docker Hub
    restart: unless-stopped
    user: mysql # overrides the root user used to run the container process
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql-db-production:/var/lib/mysql
    networks:
      - app-production
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 3s
      timeout: 5s
      retries: 5

# Network service 
networks:
  app-production:
    driver: bridge # Isolation container network with my device network

# Volumes service
volumes:
  # laravel-public-assets:
  laravel-storage-production:
  mysql-db-production:
